language: node_js

sudo: required

node_js:
  - "8"

before_install:
  - npm install -g npm@latest
  - npm install -g truffle

install:
  - npm install

jobs:
  include:
    - stage: compile
      script: truffle compile
    - stage: test
      script: truffle test
