language: node_js

sudo: required

node_js:
  - "8"

before_install:
  - npm install -g npm@latest
  - npm install -g ganache-cli
  - npm install -g truffle

install:
  - npm install

script:
  - truffle compile
  - ganache-cli -p 7545 > /dev/null &
  - truffle migrate
  - truffle test
